buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.20'
        
        // ÇÖZÜM 1: "-SNAPSHOT" hatasından kaçınmak için direkt "master" dalını hedefliyoruz.
        // Böylece Gradle, POM dosyasını sorunsuz indirip eklentiyi tanıyacak.
        classpath 'com.github.recloudstream:gradle:master'
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'com.lagradost.cloudstream3.gradle'

cloudstream {
    pluginName = "N0JEN Sync"
    pluginAuthor = "N0jen"
    pluginDescription = "AtomSpor canlı maç ve TV yayınları"
    pluginVersion = 1
    pluginTypes = ["tv"]
}

android {
    // ÇÖZÜM 2: Groovy sözdiziminde eşittir (=) işareti kullanılmaz.
    namespace 'com.n0jensync'
    compileSdk 33
    
    defaultConfig {
        minSdk 21
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

repositories {
    google()
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    // ÇÖZÜM 3: Cloudstream kütüphanesi için de aynı şekilde "master" kullanıyoruz.
    implementation 'com.github.recloudstream:Cloudstream:master'
    implementation 'org.jsoup:jsoup:1.15.3'
    
    // Güvenlik amaçlı Kotlin temel kütüphaneleri
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4'
    implementation 'com.fasterxml.jackson.module:jackson-module-kotlin:2.13.1'
}
